mod categorize_new_member;
mod descending_order;
mod regex_validate_pin_code;
mod which_are_in;
mod playing_with_digits;
mod sum_of_odd_numbers;
mod highest_scoring_word;
mod exes_and_ohs;
mod rectangle_into_squares;
mod consecutive_strings;
mod rot13;
mod duplicate_encoder;
mod cafeteria;
mod simple_substitution_cipher_helper;

pub use self::descending_order::descending_order;
pub use self::categorize_new_member::open_or_senior;
pub use self::regex_validate_pin_code::validate_pin;
pub use self::which_are_in::in_array;
pub use self::playing_with_digits::dig_pow;
pub use self::sum_of_odd_numbers::row_sum_odd_numbers;
pub use self::highest_scoring_word::high;
pub use self::exes_and_ohs::xo;
pub use self::rectangle_into_squares::sq_in_rect;
pub use self::consecutive_strings::longest_consec;
pub use self::rot13::rot13;
pub use duplicate_encoder::duplicate_encode;
